spring.datasource.url=jdbc:mysql://localhost:3306/placement_portal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Akshaya@5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.upload.dir=uploads/
server.port=8081
spring.jackson.deserialization.fail-on-null-for-primitives=false